#!/bin/bash

/htn/get_metadata
source /htn/metadata.sh

echo "Installing supervisor and virtualenv"
apt-get update
apt-get install supervisor python-pip -y
pip install virtualenv

echo "Cloning repos"
for repo in $REPOS; do
  gcloud source repos clone $repo /htn/$repo
  mkdir -p /var/log/$repo
done
